title: Cesar's Ramirez CIT_480 Blog 3

logo: /assets/img/computer.jpeg
description: A blog for Technology and tools for the CIT comunity
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
